### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by rimmesbe** [Gadget-Geek/prj-rev-bwfs-dasmoto#6]
Grade: Satisfactory

Summary: Nice job on this project, the site looks good. You used some good techniques. Take a look at the issues I created and see if you can implement the changes. Organization is going to be paramount in the next units as projects greatly increase in size and complexity. Here are some good tips as well: http://learn.shayhowe.com/html-css/writing-your-best-code/

**Comment by Gadget-Geek** [comment]
Hi Ryan,

Thanks for the helpful comments you made on my work for this project. I tried to make it look as close to what I saw on Codecademy as possible without using too much code. That being said, I definitely will improve my organization of code as I move on with this course.

Again, I appreciate the time you took to review my code.

Regards,
GG
